### ISSUE TITLE
x-target and x-arrange aren't alpine directive

### ISSUE THREAD

**Issue by delaneyj** [imacrayon/alpine-ajax#23]
Curious about this, also because x-arrange will never be used without x-target would it be `x-target.prepend.focus:foo`

**Comment by imacrayon** [comment]
`x-target` and `x-arrange` are  most often used together, but you can also combine `x-arrange` with `x-sync`.  

A single `x-target` can also map to multiple `x-arrange` “containers” like this:

```html
<form x-target=“notifications comments”>…</form>

<div id=“notifications” x-arrange=“append”>…</div>

<div id=“comments” x-arrange=“morph”>…</div>
``` 

for those use cases I think a separate attribute still makes sense.

**Comment by imacrayon** [comment]
As for them not being true directives, I don’t really have a good excuse 🙂. Alpine AJAX has gone through some API changes and the `x-` prefix has just stuck around. However, we can’t rename `x-target` to `target` because it would conflict with HTML’s `target`. Maybe one day they’ll need some modifiers or something 🤷🏼‍♂️

**Comment by imacrayon** [comment]
Will be release in v0.3
