### ISSUE TITLE
Does x-target require a form?

### ISSUE THREAD

**Issue by eydun** [imacrayon/alpine-ajax#81]
X-target is working for me when using forms. 

But if I use a simple html-link with href, then it does not work for me.

```html
<a href="/contacts" x-target="contacts">Open</a>
```

I guess that is intended behavior?

**Comment by imacrayon** [comment]
It should work. Make sure you have an `x-data` or `x-init` on the link or on a parent element too.

**Comment by W1M0R** [comment]
I also have this issue. I'm using astro with alpine. My parent component has x-data. When I click on my anchor element (with the x-target), it just follows the link. My current workaround is:

```html
<span @click="$ajax('/contacts')"></span>
```

I'm not sure if this is ideal, since the [reference documentation](https://alpine-ajax.js.org/reference/#ajax) states:

> Note: Since $ajax is intended to be used in side effects it doesn't emit any events or target x-sync elements like x-target. However, you can change these defaults using the $ajax options.

I don't really want to lose the ability to work with [ajax events](https://alpine-ajax.js.org/reference/#events), and looking at the $ajax options, I don't see anything that would enable "emitting events".

**Comment by imacrayon** [comment]
Hey, thanks for bringing this to my attention, this has changed recently and [I've updated that note to reflect](https://github.com/imacrayon/alpine-ajax/commit/06419b36045d71233589f2521fb5736f8fd96d8b) the new behavior.

To clarify, `x-target` only works on `<a>` and `<form>` elements. For other situations `$ajax()` will emit the standard events, but you'll need to use `$ajax({'sync': true, 'focus': true})` if you want to include `x-sync` elements and support elements with `autofocus`/`x-autofocus`.

**Comment by W1M0R** [comment]
Great, that's good to know, thank you @imacrayon.
